### ISSUE TITLE
test ci action run failed if pull request from forked repo

### ISSUE THREAD

**Issue by shincurry** [HackPlan/UUI#37]
```
Check payload: {"owner":"HackPlan","repo":"UUI","head_sha":"c55ac3bfd36c9f5aa6299bc7b97296a1285b3557","name":"jest-github-action","status":"completed","conclusion":"success","output":{"title":"Jest tests passed","summary":"10 tests passing in 1 suite.","annotations":[]}}
RequestError [HttpError]: Resource not accessible by integration
##[error]Resource not accessible by integration
    at /home/runner/work/_actions/mattallty/jest-github-action/v1.0.3/dist/index.js:1:153339
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 19 Aug 2020 18:58:41 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '403 Forbidden',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.antiope-preview; format=json',
    'x-github-request-id': '0780:493A:C45096:F2E822:5F3D7660',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '991',
    'x-ratelimit-reset': '1597865669',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/HackPlan/UUI/check-runs',
    headers: {
      accept: 'application/vnd.github.antiope-preview+json',
      'user-agent': 'octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"head_sha":"c55ac3bfd36c9f5aa6299bc7b97296a1285b3557","name":"jest-github-action","status":"completed","conclusion":"success","output":{"title":"Jest tests passed","summary":"10 tests passing in 1 suite.","annotations":[]}}',
    request: { hook: [Function: bound bound register], validate: [Object] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/checks#create-a-check-run'
}
```

**Comment by Sepush** [comment]
I meet the same problem when I try to PR from the forked repo.
CI test failed with the following error:
Error: Resource not accessible by integration

**Comment by shincurry** [comment]
`mattallty/jest-github-action` Action requires write permission of `{{secrets.GITHUB_TOKEN}}` to output the Coverage Report on the Pull Request comments after running the test, but pull request from forked repo don't have write permission.

https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
